version: '2.0'
services:
  torproxy:
    image: ufud/rpi-torproxy:latest
    container_name: torproxy
    restart: always
    ports:
      - "9001:9001"
      - "9030:9030"
      - "9050:9050"
      - "8118:8118"
  mysql:
    image: hypriot/rpi-mysql:latest
    container_name: mysql
    restart: always
    volumes:
       - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=toor
    ports:
      - "3306:3306"
  crawler:
    container_name: crawler
    build:
      context: .
      dockerfile: Dockerfile-crawler
    links:
      - torproxy
      - mysql
  hostcrawler:
    container_name: hostcrawler
    build:
      context: .
      dockerfile: Dockerfile-hostcrawler
    links:
      - mysql
  urlcrawler:
    container_name: urlcrawler
    build:
      context: .
      dockerfile: Dockerfile-urlcrawler
    links:
      - mysql
  titlecrawler:
  	container_name: titlecrawler
    build:
      context: .
      dockerfile: Dockerfile-titlecrawler
    links:
      - mysql
  descriptioncrawler:
  	container_name: descriptioncrawler
    build:
      context: .
      dockerfile: Dockerfile-descriptioncrawler
    links:
      - mysql
  webapp:
    container_name: webapp
    restart: always
    build:
      context: .
      dockerfile: Dockerfile-webapp
    links:
      - mysql
    ports:
      - "9000:9000"
  localtunnel:
    container_name: localtunel
    restart: always
    build:
      context: .
      dockerfile: Dockerfile-localtunnel
    links:
      - webapp
    command:
      lt --local-host webapp --port 9000 --subdomain asd01
volumes:
    mysql_data: