FROM resin/rpi-raspbian:latest

RUN apt-get update && apt-get install -y \
  mono-complete \
  mono-xsp4

WORKDIR /root
COPY . bd.machine
RUN xbuild bd.machine/bd.machine.sln

WORKDIR /root/bd.machine/src/bd.machine.webApp
ENTRYPOINT xsp4