FROM resin/rpi-raspbian:latest

RUN sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
RUN echo "deb http://download.mono-project.com/repo/debian wheezy main" | sudo tee /etc/apt/sources.list.d/mono-xamarin.list

RUN apt-get update && apt-get install -y \
  mono-complete \
  wget \
  unzip

COPY . /root/bd-machine
WORKDIR /root/bd-machine

RUN wget https://github.com/stefanmerkel/bd-machine/releases/download/0.1/packages.zip #todo nuget restore
RUN unzip packages.zip
RUN xbuild bd.machine.sln

ENTRYPOINT mono src/urlCrawler/bin/Debug/bd.machine.urlCrawler.exe