FROM resin/rpi-raspbian:latest

RUN apt-get update && apt-get install -y \
  mono-complete

WORKDIR /root
COPY . bd.machine
RUN xbuild bd.machine/bd.machine.sln

ENTRYPOINT mono bd.machine/src/crawler/bin/Debug/bd.machine.crawler.exe