version: '2.0'
services:
  torproxy:
    image: ufud/rpi-torproxy:latest
    container_name: torproxy
    restart: always
    ports:
      - "9001:9001"
      - "9030:9030"
      - "9050:9050"
      - "8118:8118"
  mysql:
    image: hypriot/rpi-mysql:latest
    container_name: mysql
    restart: always
    volumes:
       - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_DATABASE=BigData
    ports:
      - "3306:3306"
  crawler:
    container_name: crawler
    restart: always
    build:
      context: .
      dockerfile: Dockerfile-crawler
    links:
      - torproxy
      - mysql
  webapp:
    container_name: webapp
    restart: always
    build:
      context: .
      dockerfile: Dockerfile-webapp
    links:
      - mysql
    ports:
      - "9000:9000"
  localtunnel:
    container_name: localtunel
    restart: always
    build:
      context: .
      dockerfile: Dockerfile-localtunnel
    links:
      - webapp
    command:
      lt --local-host webapp --port 9000 --subdomain asd01
  #anaconda:
    #container_name: anaconda
    #restart: always
    #build:
      #context: .
      #dockerfile: Dockerfile-anaconda
    #ports:
      #- "8888:8888"
    #command: /opt/conda/bin/conda install jupyter -y --quiet && mkdir /opt/notebooks && /opt/conda/bin/jupyter notebook --notebook-dir=/opt/notebooks --ip='*' --port=8888 --no-browser
volumes:
    mysql_data: